### PR TITLE
Authorise tokens using Person model

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Comment by jnv** [comment]
Could you cherrypick 4309759f972062e24ebb2f11fef1c462d23ac195 to master and rebase?

**Comment by jirutka** [comment]
Why? o.O

**Comment by jnv** [comment]
Well, so we could deploy that independently, but never mind.
So the problem wasn't with db-side generated tokens in the first place. Do you want to implement it, still?
Anyway, :shipit:

**Comment by jirutka** [comment]
I’m not sure yet.

**Pull request merged**
