### PR TITLE
Fix invalid input syntax for uuid error in Person.id_from_token()

### PR DESCRIPTION
**Pull request by jirutka**
@jnv, review plz

### CODE REVIEW

**Comment by jnv** [comment]
Hm, fine by me, but perhaps we should catch the malformed token also on the API side, don't you think?

**Comment by jirutka** [comment]
I don’t understand, what exactly do you mean?

**Comment by jirutka** [comment]
It’s already handled on the API side, see [sirius_api/strategies/local_token](https://github.com/cvut/sirius/blob/master/lib/sirius_api/strategies/local_token.rb#L22-L24).

**Comment by jnv** [comment]
I mean GET parameters validation.

**Comment by jirutka** [comment]
I think that it would be kinda redundant. Normally I would agree with that, but this would require additional gem (for UUID validation) and it’s a type of error handling that _shouldn’t_ be fast anyway.

**Comment by jnv** [comment]
Handling this on API level would give you more specific message and would catch obvious mistakes even with regex. My point is that totally invalid token shouldn't hit database in the first place, but I won't bikeshed over this. If I remember, I'll add validation later.
:shipit:

**Comment by jirutka** [comment]
Hm, I agree that more specific message on malformed token would be a good thing. Let's address it in another PR.

**Pull request merged**
