### PR TITLE
Add attribute irregular to SemesterPeriod (fixes #172)

### LINKED ISSUE #172: Mark teaching ‘microperiods’ as exceptional
While implementing mapping of periods to calendar weeks, we have realised that we cannot unambiguously define week's overal parity.

Consider a week with 4 teaching periods:

- two periods are have odd parity,
- two periods are even

What is the overall parity of the week?

We can identify one-day periods and ignore them, consider them as exceptional, but it is an arbitrary decision on our side. However there is a domain knowledge whether this exception is permanent; perhaps these exceptional periods should be marked as such?

### PR DESCRIPTION
**Pull request by jirutka**
@flexik review plz

### CODE REVIEW

**Comment by jnv** [comment]
I wonder, why do you store this in the database? I think we have agreed in #172 that this will be just inferred on the fly from the `first_day_override`; that's much easier than modifying database until we figure out other cases where this assumption does not apply.

Anyway, I would like @flexik to handle this.

**Comment by flexik** [comment]
The PR looks fine overall. Storing the flag in the database is not a problem. I guess we would have to do that pretty soon anyway.

**Comment by jirutka** [comment]
@jnv I think that inferring regularity of an event from `first_day_override` is just a mere workaround. That’s why we’ve opened #172, isn’t it? An event may be irregular even without overriding a day. Let’s leave this decision to “timemasters.” And they still use SQL interface for write access to Sirius, so make it clear for them.

@flexik So :shipit:?

**Comment by flexik** [comment]
:ship: :it: !

**Pull request merged**
