### PR TITLE
Switch to Ruby 2.2.2

### PR DESCRIPTION
**Pull request by jnv**
So, you know, just so you notice.

### CODE REVIEW

**Comment by jnv** [comment]
cc @jirutka, @flexik

**Comment by jirutka** [comment]
I have no problem with updating to MRI 2.2.2.

**Comment by jnv** [comment]
Do we have any demo or something so I can put this up on staging?

**Comment by jirutka** [comment]
Well, we should update production before experimenting with staging, because of fittable that is currently using staging instance…

**Comment by jnv** [comment]
Okay, I will do that, merge this, update staging and go to sleep.

**Comment by jirutka** [comment]
:+1:

**Pull request merged**
