### PR TITLE
ENUMs support + other DB optimizations (WIP)

### PR DESCRIPTION
**Pull request by flexik**
This PR includes all changes from #186 and on top of that adds support for PostgreSQL ENUMs.

TODO:

- [ ] Go through database schema and refactor remaining columns that can be converted into ENUMs (most of the work is done, it should be only a few columns).
- [ ] Check `room_id` of generated events, in my testing it was sometimes `nil` when it shouldn't.

### CODE REVIEW

**Comment by jnv** [comment]
Thanks! Do you think we could handle refactoring to Enum in a separate PR so we can finally merge this?

**Comment by jirutka** [comment]
@jnv What do you think that he did here...?! The upsert PR was not supposed to be closed.

**Comment by jnv** [comment]
@jirutka Oh, sorry, didn't know that. I will resolve merge conflicts on that branch then.

**Comment by jirutka** [comment]
Replaced by #212.

**Pull request closed without merging**
