### PR TITLE
Reenable all Rake tasks after each run in scheduler (fixes #152)

### LINKED ISSUE #152: Scheduler stops working correctly after first run
For some reason the import scheduler currently runs scheduled import tasks only once after application restart. On subsequent runs it logs that the import has started, but ends up immediately without any rake tasks being executed.

Scheduler logs (I have set scheduler to run every 3rd hour for testing purposes on staging): 
```
INFO  [scheduler]: Setting automatic sync to '0 */3 * * *'
rake-jekyll is not available
INFO  [SyncHandler]: Scheduled import started.
INFO  [sirius.rake]: Importing parallels.
INFO  [sirius.rake]: Importing students, grab a coffee.
INFO  [sirius.rake]: Planning parallels.
INFO  [sirius.rake]: Assigning people to events.
INFO  [sirius.rake]: Importing exams.
INFO  [sirius.rake]: Importing exam students.
INFO  [sirius.rake]: Importing course events.
INFO  [sirius.rake]: Importing course event students.
INFO  [sirius.rake]: Renumbering events.
Resetting index sirius_multi_search
  Imported MultiSearchIndex::Course for 1.02s, documents total: 1539
  Imported MultiSearchIndex::Person for 4.24s, documents total: 8039
  Imported MultiSearchIndex::Room for 0.08s, documents total: 234
INFO  [SyncHandler]: Scheduled import finished. Time taken: 1671.438163053 s.
INFO  [SyncHandler]: Scheduled import started.
INFO  [SyncHandler]: Scheduled import finished. Time taken: 0.000275404 s.
INFO  [SyncHandler]: Scheduled import started.
INFO  [SyncHandler]: Scheduled import finished. Time taken: 0.000338997 s.
INFO  [SyncHandler]: Scheduled import started.
INFO  [SyncHandler]: Scheduled import finished. Time taken: 0.000307697 s.
```

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Comment by jnv** [comment]
I see, the issue is that rake runs in-process. Perhaps we could move it out, somehow?

**Comment by flexik** [comment]
It seems to be working on staging for now. Just one small issue with this solution is that after an error is thrown during import, the rake tasks would get skipped once on the following run (because `Rake::Task.tasks.each(&:reenable)` is not getting called).

See logs:
```
  70287089475600     work_queue: 0
} 70287089475600 .             <- end of error message being thrown from import
INFO  [SyncHandler]: Scheduled import started.
INFO  [SyncHandler]: Scheduled import finished. Time taken: 0.000388072 s.
INFO  [SyncHandler]: Scheduled import started.
INFO  [sirius.rake]: Importing parallels.
INFO  [sirius.rake]: Importing students, grab a coffee.
INFO  [sirius.rake]: Planning parallels.
INFO  [sirius.rake]: Assigning people to events.
INFO  [sirius.rake]: Importing exams.
INFO  [sirius.rake]: Importing exam students.
INFO  [sirius.rake]: Importing course events.
INFO  [sirius.rake]: Importing course event students.
INFO  [sirius.rake]: Renumbering events.
Resetting index sirius_multi_search
  Imported MultiSearchIndex::Course for 1.45s, documents total: 1541
  Imported MultiSearchIndex::Person for 4.48s, documents total: 8148
  Imported MultiSearchIndex::Room for 0.1s, documents total: 234
INFO  [SyncHandler]: Scheduled import finished. Time taken: 1463.797603435 s.
```

**Comment by jirutka** [comment]
Hmm, what about this…?

```rb
begin
  Rake::Task['sirius:events'].invoke
ensure
  Rake::Task.tasks.each(&:reenable)
end
```

**Comment by flexik** [comment]
It should do the trick. Or just call reenable before invoke. :bowtie:

**Comment by jirutka** [comment]
Hm, too simple, but… yeah.

**Comment by jirutka** [comment]
It’s a very simple patch that fixes #152 and we verified that it’s working, so I’m merging it.

**Pull request merged**
