### PR TITLE
Add helper for pagination and make schedule_exceptions endpoint paginable

### PR DESCRIPTION
**Pull request by jirutka**
/cc @flexik

### CODE REVIEW

**Comment by jnv** [comment]
Why are you mixing corefines functionality with roar's? This will blow up in our face.

**Comment by jirutka** [comment]
What do you mean with mixing? I’m using just few convenient refinements for Hash. I don’t see any problem here.

**Comment by jirutka** [comment]
@jnv ping

**Comment by jnv** [comment]
pong

**Comment by jirutka** [comment]
@jnv Okay, maybe I haven’t been clear. Could yo please do a code-review? :cat:

**Comment by jnv** [comment]
Well, there's a duplication of pagination functionality. As for refinements, you're overriding Roar's functionality which can be difficult in case we would like to use bidirectional serialization.

Either way, I think this refactoring is pointless now, first there should be additional resources and functionality, then we should refactor duplicated functionality. Otherwise you may end up undoing these changes.

**Comment by flexik** [comment]
I've changed the implementation a bit, making it more reusable for other resources.

**Comment by jirutka** [comment]
:+1:

**Pull request merged**
