### PR TITLE
ENUMs support + other DB optimizations (rebased)

### PR DESCRIPTION
**Pull request by jirutka**
This PR adds support for PostgreSQL ENUMs.

**TODO:**

- [x] Go through database schema and refactor remaining columns that can be converted into ENUMs (most of the work is done, it should be only a few columns).
    - [x] Create enum `semester_period_type` for table `semester_periods`.
- [x] Enable EnumGuard plugin globally
- [x] Try to run import pipeline to ensure that it’s really okay.

**Questions:**

- Use symbols instead of strings for enums in Ruby code as before?

Replaces #203.

### CODE REVIEW

**Comment by jnv** [comment]
This needs to refresh seeds.

**Comment by jnv** [comment]
Also, running migrations against production data fails (so far) with `schedule_exceptions` table, which has empty `created_at` and `updated_at` fields.

**Comment by jnv** [comment]
I wonder, do you think we could wrap Ruby string into some Enum types?

**Comment by jnv** [comment]
Well, [pg_enum](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/extensions/pg_enum.rb) should support typecasting to/from symbols, so I am not sure why everything was turned to strings.

There is also [sequel_enum](https://github.com/planas/sequel_enum) plugin, which provides some sugar and visibility for enums.

**Comment by jirutka** [comment]
I’ve squashed fixups and slightly reworded one commit subject. I’m gonna merge it after CI pass.

**Pull request merged**
