### PR TITLE
Renew Umapi OAuth access token on 401 status

### LINKED ISSUE #161: Renew access token when Umapi returns 401
When resource provider returns 401, it usually means that an access token has expired and you must obtain a new one. We’re not doing it now… or to be more specific, [oauth2](https://github.com/intridea/oauth2) gem is not doing it. We rely solely on `expires_in` attribute (number of seconds to expiration), but this is not 100% reliable (think about delays on network etc).

BTW, I think that we should look at a better oauth gem, [oauth2](https://github.com/intridea/oauth2) is not very good.

### PR DESCRIPTION
**Pull request by flexik**
This PR resolves #161 and #156.

### CODE REVIEW

**Comment by jirutka** [comment]
How it resolves #156 ? It still depends on existence of user `szolatib` with some roles in production Umapi.

**Comment by flexik** [comment]
The HTTP client is stubbed, so the spec does not send any requests anymore. We can change the roles and usernames to some dummy values now.

**Comment by jirutka** [comment]
Maybe I’m blind, but I don’t see it in the code. Where is the stub defined?

**Comment by flexik** [comment]
In `umapi_client_spec.rb`, line 14 stubs `#token` method on `UmapiClient` instance, returning `token` stub defined on line 9.

**Comment by jirutka** [comment]
Ah, I see now! This OAuth lib has really extremely stupid API; calling requests on the token object…

**Comment by flexik** [comment]
Welp, yes it does...

**Comment by jirutka** [comment]
:shipit:

**Pull request merged**
