### PR TITLE
Allow teachers to get all calendars

### PR DESCRIPTION
**Pull request by jirutka**
This is a temporary solution for #99.

### CODE REVIEW

**Comment by jnv** [comment]
This is fugly. I don't like it. Whatever, just mark it as `FIXME` and :shipit:

**Comment by jirutka** [comment]
Can you be more specific, what do you don’t like about it?

**Comment by jnv** [comment]
The very logic of this fix is flawed. The proper fix would use actual role permissions, the mid-term fix would add a permission attribute, but it's suitable as a _temporary_ fix.

**Comment by jirutka** [comment]
Okay, I’ve updated it.

**Pull request merged**
